# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PrGW7tRzW2oGCxYOsS05zRsTT8qxqLKv
"""

def add(a,b):
  return a+b

print(add(2,3))

print(add(10,3))

print(add(10,30))

